apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-k8s-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-k8s-deployment
    spec:
      containers:
      - name: hello-k8s-deployment
        image: souvikmukherjeedocker/spring-k8s-svc:latest
        ports:
        - name: hello-k8s-deployment-port
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 30
