apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-deployment-lb-svc
  labels:
    name: hello-k8s-deployment-lb-svc
spec:
  ports:
  - port: 8080
    targetPort: hello-k8s-deployment-port
    protocol: TCP
  selector:
    app: hello-k8s-deployment
  type: LoadBalancer
