apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-k8s-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-k8s-deployment
    spec:
      containers:
      - name: hello-k8s-deployment
        image: souvikmukherjeedocker/spring-k8s-svc:latest
        ports:
        - containerPort: 8080
