apiVersion: v1
kind: Service
metadata:
    name: hello-k8s-lb-svc
spec:
    ports:
    -   port: 8080
        targetPort: hello-k8s-port
        protocol: TCP
    selector:
        app: hello-k8s
    type: LoadBalancer
