apiVersion: v1
kind: Pod
metadata:
    name: hello-k8s
    labels:
        app: hello-world
spec:
    containers:
    -   name: spring-k8s-demo
        image: souvikmukherjeedocker/spring-k8s-svc
        ports:
        -   name: hello-k8s-port
            containerPort: 3000
